root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-empty-interface': off
