using BedrockLauncher.Classes.Launcher;
using BedrockLauncher.Classes;
using BedrockLauncher.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Data;
using PostSharp.Patterns.Model;
using BedrockLauncher.ViewModels;
using JemExtensions;

namespace BedrockLauncher.Handlers
{
    public class FilterSortingHandler
    {
        public static SortDescription? GetInstallationSortDescriptor()
        {
            switch (Properties.LauncherSettings.Default.InstallationsSortMode)
            {
                case InstallationSort.LatestPlayed:
                    return new SortDescription(nameof(BLInstallation.LastPlayedT), ListSortDirection.Descending);
                case InstallationSort.Name:
                    return new SortDescription(nameof(BLInstallation.DisplayName), ListSortDirection.Ascending);
                case InstallationSort.None:
                    return null;
                default:
                    return new SortDescription(nameof(BLInstallation.LastPlayedT), ListSortDirection.Descending);
            }
        }
        public static string InstallationsSearchFilter { get; set; } = string.Empty;

        public static void Refresh(object itemSource)
        {
            var view = CollectionViewSource.GetDefaultView(itemSource) as CollectionView;
            if (view != null) view.Refresh();
        }
        public static void Sort_InstallationList(object itemSource)
        {
            var view = CollectionViewSource.GetDefaultView(itemSource) as CollectionView;
            if (view != null)
            {
                view.SortDescriptions.Clear();
                var result = GetInstallationSortDescriptor();
                if (result != null) view.SortDescriptions.Add(result.Value);
                view.Refresh();
            }
        }

        public static bool Filter_InstallationList(object obj)
        {
            BLInstallation v = obj as BLInstallation;
            if (v == null) return false;
            else if (!Properties.LauncherSettings.Default.ShowPreviews && v.IsPreview) return false;
            else if (!Properties.LauncherSettings.Default.ShowBetas && v.IsBeta) return false;
            else if (!Properties.LauncherSettings.Default.ShowReleases && v.IsRelease) return false;
            else if (!v.DisplayName.Contains(InstallationsSearchFilter)) return false;
            else return true;
        }
        public static bool Filter_PlayInstallationList(object obj)
        {
            BLInstallation v = obj as BLInstallation;
            if (v == null) return false;
            if (!Properties.LauncherSettings.Default.ShowPreviews && v.IsPreview) return false;
            if (!Properties.LauncherSettings.Default.ShowBetas && v.IsBeta) return false;
            if (!Properties.LauncherSettings.Default.ShowReleases && v.IsRelease) return false;
            if (HasUserInstallations() && IsAutoGeneratedPlayInstallation(v)) return false;
            if (IsFloatingInstallation(v)) return false;
            if (v.Version == null) return false;
            if (v.IsPlayableInstalled != true) return false;
            return true;
        }
        public static bool Filter_VersionList(object obj)
        {
            MCVersion v = (obj as MCVersion);
            if (v != null)
            {
                if (Properties.LauncherSettings.Default.ShowPreviews && v.IsPreview) return true;
                else if (Properties.LauncherSettings.Default.ShowBetas && v.IsBeta) return true;
                else if (Properties.LauncherSettings.Default.ShowReleases && v.IsRelease) return true;
                else return false;
            }
            else return false;

        }

        public static bool Filter_OfficalNewsFeed(object obj)
        {
            if (!(obj is News_OfficalItem)) return false;
            else
            {
                var item = (obj as News_OfficalItem);
                if (item.newsType == null || !item.newsType.Contains("News page")) return false;
                if (item.category != "Minecraft for Windows") return false;
                if (!NewsViewModel.Default.Offical_ShowBedrockContent) return false;
                return ContainsText(item);
            }

            bool ContainsText(News_OfficalItem _item)
            {
                string searchParam = NewsViewModel.Default.Offical_SearchBoxText;
                if (string.IsNullOrEmpty(searchParam) || _item.title.Contains(searchParam, StringComparison.OrdinalIgnoreCase)) return true;
                else return false;
            }
        }

        private static bool IsFloatingInstallation(BLInstallation installation)
        {
            return installation.VersionUUID == Constants.LATEST_RELEASE_UUID ||
                   installation.VersionUUID == Constants.LATEST_PREVIEW_UUID ||
                   installation.VersionUUID == Constants.LATEST_BETA_UUID ||
                   installation.InstallationUUID == Constants.LATEST_RELEASE_UUID ||
                   installation.InstallationUUID == Constants.LATEST_PREVIEW_UUID ||
                   installation.InstallationUUID == Constants.LATEST_BETA_UUID;
        }

        public static bool HasUserInstallations()
        {
            return MainDataModel.Default?.Config?.CurrentInstallations?.Any(installation =>
                installation != null &&
                !IsAutoGeneratedPlayInstallation(installation) &&
                !IsFloatingInstallation(installation) &&
                installation.Version != null) == true;
        }

        public static bool IsAutoGeneratedPlayInstallation(BLInstallation installation)
        {
            if (installation == null) return false;
            if (!installation.ReadOnly) return false;

            return installation.InstallationUUID?.StartsWith("versions_page_selected:", StringComparison.OrdinalIgnoreCase) == true ||
                   installation.InstallationUUID?.StartsWith("system_minecraft:", StringComparison.OrdinalIgnoreCase) == true ||
                   installation.InstallationUUID?.StartsWith("catalog_version:", StringComparison.OrdinalIgnoreCase) == true ||
                   IsFloatingInstallation(installation);
        }
    }
}
