//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BedrockLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BedrockLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bedrock.png
        ///bookshelf.png
        ///bricks.png
        ///cake.png
        ///pumpkin.png
        ///chest.png
        ///clay.png
        ///block_of_coal.png
        ///coal_ore.png
        ///cobblestone.png
        ///crafting_table.png
        ///creeper_head.png
        ///block_of_diamond.png
        ///diamond_ore.png
        ///dirt.png
        ///podzol.png
        ///snowy_grass_block.png
        ///block_of_emerald.png
        ///emerald_ore.png
        ///enchanting_table.png
        ///end_stone.png
        ///farmland.png
        ///furnace.png
        ///lit_furnace.png
        ///glass.png
        ///light_blue_glazed_terracotta.png
        ///orange_glazed_terracotta.png
        ///white_glazed_terracotta.png
        ///glowstone.png
        ///block_of_gold.png [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _BlockOrder {
            get {
                return ResourceManager.GetString("_BlockOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .body {
        ///            background-color: #262626;
        ///        }
        ///
        ///        .cssload-thecube {
        ///            width: 73px;
        ///            height: 73px;
        ///            margin: 0 auto;
        ///            margin-top: 49px;
        ///            position: relative;
        ///            transform: rotateZ(0deg);
        ///            -o-transform: rotateZ(0deg);
        ///            -ms-transform: rotateZ(0deg); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Loader {
            get {
                return ResourceManager.GetString("Loader", resourceCulture);
            }
        }
    }
}
