<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
	<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\lang\.ext\**\*.*" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\lang\.ext\**\*.*" />
	</ItemGroup>
	<ItemGroup>
		<Page Remove="Resources\lang\lang.default.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>PublicSettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Resources\lang\.ext\" />
	</ItemGroup>

</Project>
