blank_issues_enabled: false
contact_links:
    - name: Suggestions or feature request
      url: https://github.com/BedrockLauncher/BedrockLauncher/discussions/categories/ideas
      about: Got something you think should change or be added? Search for or start a new discussion!
    - name: Pulls
      url: https://github.com/BedrockLauncher/BedrockLauncher/compare
      about: Finish the idea of coding and going to propose? Go ahead!
    - name: Unsure an issue
      url: https://github.com/BedrockLauncher/BedrockLauncher/discussions/categories/q-a
      about: Got something but unsure it's either a bug or whatever? Come here and ask other cool people and devs!

