<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../BedrockLauncher/Handlers/MinecraftManifestPatcher.cs" Link="MinecraftManifestPatcher.cs" />
    <Compile Include="../../BedrockLauncher/Handlers/PackageRegistrationMatcher.cs" Link="PackageRegistrationMatcher.cs" />
  </ItemGroup>
</Project>
