using System.Linq;
using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Threading;
using BedrockLauncher.Classes;
using BedrockLauncher.Handlers;
using BedrockLauncher.ViewModels;

namespace BedrockLauncher.Pages.Play.Home.Components
{
    /// <summary>
    /// Interaction logic for InstallationSelector.xaml
    /// </summary>
    public partial class InstallationSelector : ComboBox
    {
        private bool refreshQueued;

        public InstallationSelector()
        {
            InitializeComponent();
            DataContext = MainDataModel.Default;
        }
        private void ComboBox_Loaded(object sender, RoutedEventArgs e)
        {
            RefreshInstallationsFromDisk();
            Dispatcher.BeginInvoke(new System.Action(RefreshInstallationsFromDisk), DispatcherPriority.Background);
        }

        private void ComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (SelectedItem is BLInstallation selectedInstallation &&
                FilterSortingHandler.HasUserInstallations() &&
                FilterSortingHandler.IsAutoGeneratedPlayInstallation(selectedInstallation))
            {
                ScheduleSelectorRefresh();
            }
        }

        private void ComboBox_SourceUpdated(object sender, DataTransferEventArgs e)
        {
            RefreshInstallationsFromDisk();
        }

        private void ComboBox_DropDownOpened(object sender, EventArgs e)
        {
            RefreshInstallationsFromDisk();

            if (SelectedItem is BLInstallation selectedInstallation &&
                FilterSortingHandler.HasUserInstallations() &&
                FilterSortingHandler.IsAutoGeneratedPlayInstallation(selectedInstallation))
            {
                IsDropDownOpen = false;
                ScheduleSelectorRefresh();
            }
        }

        private void RefreshInstallationsFromDisk()
        {
            BLInstallation selectedInstallation = MainDataModel.Default.Config.EnsurePlayableInstallationSelected(forceSync: true);
            var playableInstallations = MainDataModel.Default.Config.GetPlayableInstallationsSnapshot();

            SetCurrentValue(ItemsControl.ItemsSourceProperty, playableInstallations);
            CollectionView view = CollectionViewSource.GetDefaultView(ItemsSource) as CollectionView;
            if (view != null)
            {
                view.Filter = FilterSortingHandler.Filter_PlayInstallationList;
                view.Refresh();
            }

            if (selectedInstallation == null || !FilterSortingHandler.Filter_PlayInstallationList(selectedInstallation))
                selectedInstallation = view?.Cast<BLInstallation>().FirstOrDefault();

            if (selectedInstallation != null)
            {
                SetCurrentValue(Selector.SelectedValueProperty, selectedInstallation.InstallationUUID);
                SetCurrentValue(Selector.SelectedItemProperty, selectedInstallation);
            }
            else
            {
                SetCurrentValue(Selector.SelectedValueProperty, MainDataModel.Default.Config.CurrentInstallationUUID);
                SetCurrentValue(Selector.SelectedItemProperty, MainDataModel.Default.Config.CurrentInstallation);
            }

            FilterSortingHandler.Sort_InstallationList(ItemsSource);
        }

        private void ScheduleSelectorRefresh()
        {
            if (refreshQueued)
                return;

            refreshQueued = true;
            Dispatcher.BeginInvoke(new Action(() =>
            {
                refreshQueued = false;
                RefreshInstallationsFromDisk();
            }), DispatcherPriority.Render);
        }

        private void CollectionViewSource_Filter(object sender, FilterEventArgs e)
        {
            e.Accepted = FilterSortingHandler.Filter_InstallationList(e.Item);
        }
    }
}
