name: Build Test

on:
  push:
    branches: '*'
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Checkout submodules
        run: git submodule update --remote --init --recursive

      - name: Use GitHub build targets
        shell: bash
        run: |
          cp -f "${GITHUB_WORKSPACE}/BedrockLauncher/GitHub.Directory.Build.targets" "${GITHUB_WORKSPACE}/BedrockLauncher/Directory.Build.targets" 
        
      - name: Setup nuget
        uses: nuget/setup-nuget@v1

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore dependencies
        run: nuget restore BedrockLauncher.sln

      - name: Build
        run: msbuild "BedrockLauncher.sln"

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: BedrockLauncher/bin/Debug/net*.*-windows*.*.*.*
