name: Build Test

on:
  push:
    branches: ["workflow-test"] # workflow-test is here temporarily, make master later
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup nuget
        uses: nuget/setup-nuget@v1

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore dependencies
        run: nuget restore BedrockLauncher.sln

      - name: Build
        run: msbuild "BedrockLauncher.sln"

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ./
